### ISSUE TITLE
Links not clickable (Chrome)

### ISSUE THREAD

**Issue by oppenheimer-** [Heydon/ga11ery#17]
When you open the info box and close it again, all links on the page are left unclickable.

It seems to happen on Chrome (mine is Version 80.0.3987.163). Firefox / Safari look good though.

**Comment by Heydon** [comment]
@oppenheimer Wow, that's a weird one. I'll take a look.

**Comment by Heydon** [comment]
@oppenheimer I have the same version of Chrome but can't reproduce this. Are you on MacOS?

**Comment by oppenheimer-** [comment]
yep, Catalina 10.15.3 and no js errors

**Comment by Heydon** [comment]
@oppenheimer Hmm. I'm on Mojave. Thanks again for reporting. I'll ask on Twitter if anyone can reproduce the bug.

**Comment by ndorfin** [comment]
Also happens for me:

1. Go to https://goofy-nightingale-8088ae.netlify.com/
1. Click the '[?]' link in the header for the CERN image. <img width="548" alt="" src="https://user-images.githubusercontent.com/107569/79041269-253b4000-7bf7-11ea-863c-00cf79e099f4.png">

Popover displays a message. Have to click the [close] link.
After clicking the

**Comment by ndorfin** [comment]
Seems the problem starts with this line:

`wrapper.setAttribute('inert', 'inert')`

When the user clicks the close button, the `wrapper`'s `inert` attribute is never removed. Running this after the close button is clicked, fixed it for me:

`document.querySelector('div.wrapper').removeAttribute('inert')`

**Comment by Heydon** [comment]
@ndorfin Ahh. That makes sense; completely forgot to remove the attribute! Will fix now.

**Comment by Heydon** [comment]
Okay, this is sorted in the 0.1.2 release (see also b5e3aa0318c153d1a227b11b0050f3020a1e4770)

Thanks for the heads-up!
